---
kind: pipeline
type: docker
name: abebars-io

steps:
- name: build-docs
  image: squidfunk/mkdocs-material:3.2.0
  commands:
    - pip install mkdocs-minify-plugin
    - pip install mkdocs-git-revision-date-localized-plugin
    - mkdocs build
  when:
    event: push
    branch: main

- name: deploy-aws-s3
  image: plugins/s3
  settings:
    bucket: abebars.io
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: site/**/*
    target: /
    strip_prefix: site/
  when:
    event: push
    branch: main
